name: Deploy Production (Blue/Green, local)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Existing local tag (commit SHA or 'main')"
        required: true
        type: string

jobs:
  prod-bluegreen:
    runs-on: self-hosted
    environment:
      name: production
      url: http://localhost:8080

    steps:
      - name: Verify image exists locally (no build)
        run: |
          set -e
          IMAGE=php-hello
          TAG="${{ inputs.image_tag }}"
          docker image inspect ${IMAGE}:${TAG} >/dev/null 2>&1 || {
            echo "Image ${IMAGE}:${TAG} not found locally."; exit 1; }

      - name: Decide colors (blue on first run, else promote idle)
        id: colors
        run: |
          set -e
          blue_running=$(docker ps --format '{{.Names}}' | grep -w '^php-hello-blue$' || true)
          green_running=$(docker ps --format '{{.Names}}' | grep -w '^php-hello-green$' || true)
          if [ -z "$blue_running$green_running" ]; then
            ACTIVE=""
            TARGET="blue"        # first run
          else
            if [ -n "$blue_running" ]; then ACTIVE="blue"; TARGET="green"; else ACTIVE="green"; TARGET="blue"; fi
          fi
          echo "active=$ACTIVE" >> $GITHUB_OUTPUT
          echo "target=$TARGET" >> $GITHUB_OUTPUT

      - name: Start target backend and health-check
        id: backend
        run: |
          set -e
          IMAGE=php-hello
          TAG="${{ inputs.image_tag }}"
          NET=php-hello-net
          TARGET="${{ steps.colors.outputs.target }}"

          docker network create $NET 2>/dev/null || true

          docker rm -f php-hello-${TARGET} 2>/dev/null || true
          docker run -d --name php-hello-${TARGET} --restart unless-stopped \
            --network $NET ${IMAGE}:${TAG}

          for i in {1..40}; do
            docker exec php-hello-${TARGET} sh -lc "wget -qO- http://127.0.0.1/health >/dev/null" && break || sleep 1
          done
          docker exec php-hello-${TARGET} sh -lc "wget -qO- http://127.0.0.1/health" >/dev/null

      - name: Write single nginx config (override default.conf)
        id: config
        run: |
          set -e
          GDIR="$HOME/.php-hello-gateway"
          TARGET="${{ steps.colors.outputs.target }}"
          mkdir -p "$GDIR"

          # One file containing upstream + server; becomes default.conf inside container
          cat > "$GDIR/proxy.conf" <<NGINX
          upstream app_upstream { server php-hello-${TARGET}:80; }

          server {
            listen 80 default_server;
            server_name _;
            location / {
              proxy_pass http://app_upstream;
              proxy_set_header Host \$host;
              proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            }
          }
          NGINX

          # Ensure any old confs we might have written aren't around
          rm -f "$GDIR"/site.conf "$GDIR"/upstream.conf "$GDIR"/upstream-*.conf || true

      - name: Start or reload gateway with our config only
        run: |
          set -e
          NET=php-hello-net
          GDIR="$HOME/.php-hello-gateway"
          GW=php-hello-gateway

          # If gateway exists but isn't running, remove it
          if docker ps -a --format '{{.Names}} {{.Status}}' | grep -q "^${GW}\b"; then
            docker ps --format '{{.Names}}' | grep -q "^${GW}$" || docker rm -f $GW || true
          fi

          if docker ps --format '{{.Names}}' | grep -q "^${GW}$"; then
            # Replace config (bind mount already points to proxy.conf), just reload
            docker exec $GW nginx -t || { docker logs $GW; exit 1; }
            docker exec $GW nginx -s reload || true
          else
            # Start fresh, shadow default vhost by mounting our file at default.conf
            docker rm -f $GW 2>/dev/null || true
            docker run -d --name $GW --restart unless-stopped \
              --network $NET -p 8080:80 \
              -v "$GDIR/proxy.conf:/etc/nginx/conf.d/default.conf:ro" \
              nginx:stable
            sleep 1
            docker exec $GW nginx -t || { docker logs $GW; exit 1; }
          fi

      - name: Stop old color (if any)
        if: steps.colors.outputs.active != ''
        run: |
          set -e
          OLD="${{ steps.colors.outputs.active }}"
          docker rm -f php-hello-${OLD} 2>/dev/null || true

      - name: Smoke test gateway
        run: |
          for i in {1..30}; do curl -fsS http://localhost:8080/health && exit 0; sleep 1; done
          echo "Prod gateway health failed"; docker logs php-hello-gateway || true; exit 1
